DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0031.js", "first": "1", "last": "11" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "2025" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "3" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "4" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "5" },
	{ "fileName": "0xu0036.js", "first": "6", "last": "6" },
	{ "fileName": "0xu0037.js", "first": "7", "last": "7" },
	{ "fileName": "0xu0038.js", "first": "8", "last": "8" },
	{ "fileName": "0xu0039.js", "first": "9", "last": "9" },
	{ "fileName": "0xu0042.js", "first": "BASE", "last": "BASE" },
	{ "fileName": "0xu0044.js", "first": "DR", "last": "DR.EXPLAIN" },
	{ "fileName": "0xu0045.js", "first": "EMAIL", "last": "EXPLAIN" },
	{ "fileName": "0xu0046.js", "first": "FASHION", "last": "FLORA" },
	{ "fileName": "0xu004c.js", "first": "LOFT", "last": "LOFT" },
	{ "fileName": "0xu0404.js", "first": "ЄР", "last": "ЄРУ" },
	{ "fileName": "0xu0406.js", "first": "І", "last": "ІСТОРІЯ" },
	{ "fileName": "0xu0407.js", "first": "ЇЇ", "last": "ЇЇ" },
	{ "fileName": "0xu0410.js", "first": "А", "last": "АСИСТЕНТА" },
	{ "fileName": "0xu0411.js", "first": "БІЛЬШЕ", "last": "БУТИ" },
	{ "fileName": "0xu0412.js", "first": "В", "last": "ВХОДУ" },
	{ "fileName": "0xu0413.js", "first": "ГАРЯЧІ", "last": "ГОЛОВНА" },
	{ "fileName": "0xu0414.js", "first": "ДАЄ", "last": "ДОСТУПНОСТІ" },
	{ "fileName": "0xu0415.js", "first": "ЕКОНОМІЇ", "last": "ЕЛЕМЕНТИ" },
	{ "fileName": "0xu0416.js", "first": "ЖИВИМИ", "last": "ЖИВИМИ" },
	{ "fileName": "0xu0417.js", "first": "З", "last": "ЗРУЧНОСТІ" },
	{ "fileName": "0xu041a.js", "first": "КІЛЬКІСТЬ", "last": "КОРОТКИЙ" },
	{ "fileName": "0xu041b.js", "first": "ЛЕГКО", "last": "ЛОКАЦІЇ" },
	{ "fileName": "0xu041c.js", "first": "М", "last": "М’ЯКЕ" },
	{ "fileName": "0xu041d.js", "first": "НА", "last": "НОМЕР" },
	{ "fileName": "0xu041e.js", "first": "ОБЕРІТЬ", "last": "ОЦІНИТИ" },
	{ "fileName": "0xu041f.js", "first": "ПІД", "last": "ПРОЦЕС" },
	{ "fileName": "0xu0420.js", "first": "РІЗНІ", "last": "РУКОВОДСТВО" },
	{ "fileName": "0xu0421.js", "first": "СІМЕЙНИХ", "last": "СТУДІЮ" },
	{ "fileName": "0xu0422.js", "first": "ТА", "last": "ТРИВАЛОСТІ" },
	{ "fileName": "0xu0423.js", "first": "У", "last": "УСПІШНОЇ" },
	{ "fileName": "0xu0424.js", "first": "ФОН", "last": "ФУНКЦІЯ" },
	{ "fileName": "0xu0425.js", "first": "ХАРАКТЕРИСТИКИ", "last": "ХАРАКТЕРИСТИКИ" },
	{ "fileName": "0xu0426.js", "first": "ЦІЙ", "last": "ЦЯ" },
	{ "fileName": "0xu0427.js", "first": "ЧАС", "last": "ЧИ" },
	{ "fileName": "0xu0428.js", "first": "ШВИДКІ", "last": "ШВИДКО" },
	{ "fileName": "0xu0429.js", "first": "ЩО", "last": "ЩОДО" },
	{ "fileName": "0xu042f.js", "first": "Я", "last": "ЯКЩО" }
];